services:
  - type: web
    name: backend-hyyevents
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_CACHE_DIR
        value: '/usr/src/app/.cache/puppeteer'
      - key: PUPPETEER_EXECUTABLE_PATH
        value: '/usr/bin/google-chrome'
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'true'